// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 测试分层（设计 §8.2 的 L0–L6）。
 */
export type Layer = "l0" | "l1" | "l2" | "l3" | "l4" | "l5" | "l6";
