// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 任务结论。
 */
export type TaskOutcome = "passed" | "failed" | "skipped" | "errored" | "inconclusive";
